//! Shared LoRa wire format for the bidirectional (half-duplex) FPV head-tracking link.
//!
//! Two directions, two messages, defined exactly once here and depended on by both node binaries:
//!   - [`Control`]   (goggle node -> truck node): pan/tilt head-tracking command (raw PPM pulse width in
//!     microseconds per axis, ~1000-2000 us, ~1500 us = center) plus a `flags` command word (bit0 = re-home).
//!   - [`Telemetry`] (truck node  -> goggle node): GPS-derived status — ground speed (cm/s), satellites, fix
//!     quality (0 = no fix), and the truck-computed distance/bearing to its home point (gated by `nav_valid`).
//!
//! Generated by micropb-gen (no_std + no-alloc, proto3). All fields are scalar uint32/bool, so no container type
//! is configured and there is nothing to allocate. Encode a message into a `heapless::Vec<u8, N>` with a
//! `micropb::PbEncoder` via `MessageEncode::encode`; decode a received slice with `MessageDecode::decode_from_bytes`.

#![no_std]

// micropb emits the generated types under a module named after the proto `package` (headtrack). Keep that module
// private and re-export the message types flat so consumers write `use proto::Control;` / `use proto::Telemetry;`.
// micropb's generated code uses SCREAMING_CASE type parameters and re-imports traits it does not always use; those
// are codegen artifacts, not our code, so silence the lints rather than chase them across regenerations.
#[allow(non_camel_case_types, unused_imports, unused_parens, clippy::all)]
mod generated {
  include!(concat!(env!("OUT_DIR"), "/headtrack.rs"));
}

pub use generated::headtrack_::{Control, Telemetry};
